# https://taskfile.dev
version: '3'

tasks:
  test:
    desc: Run unit tests
    cmds:
      - go test -coverprofile=c.out ./...

  coverage:
    desc: Run unit tests and code coverage
    cmds:
      - task: test
      - go tool cover -html=c.out

  watch:
    desc: Run unit tests and rerun on file changes
    cmds:
      - ginkgo watch ./...
