name: build-docs

on:
  pull_request:
    branches: [ main ]
    paths:
    - 'docs/**'
    - 'cmd/**'
    - 'core/**'
    - '*/CHANGELOG.md'
  workflow_dispatch:
    inputs:
      deploy:
        description: 'deploy the built docs'
        type: boolean
        default: false
        required: false

jobs:
  build:
    name: Build Docs
    runs-on: ubuntu-20.04
    steps:

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Check out code
      uses: actions/checkout@v3

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.6.0
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build docs
      run: make docs-release

    - name: Deploy Docs
      if: "${{ github.event.inputs.deploy }}"
      uses: peaceiris/actions-gh-pages@v3.9.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/public
        cname: changie.dev
