name: release

on:
  push:
    branches: [ main ]
    paths: [ CHANGELOG.md ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Add env vars
        run: |
          echo GORELEASER_CURRENT_TAG=$(go run main.go latest) >> $GITHUB_ENV
          echo RELEASE_NOTES_PATH=changes/$(go run main.go latest).md >> $GITHUB_ENV

      - name: install GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          install-only: true

      - name: Run GoReleaser
        run: |
          goreleaser --rm-dist --release-notes=${RELEASE_NOTES_PATH} --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
